### ISSUE TITLE
mud client timeout

### ISSUE THREAD

**Issue by bessa** [angt/glorytun#15]
when restarting mud server side, client failed to re-establish the connection.

timeout parameter on client side seems useless.

**Comment by jedisct1** [comment]
![Holly shit](http://webmeme.altervista.org/wp-content/uploads/2011/05/holy-shit-cat.jpg)

**Comment by angt** [comment]
Hi Bash !
Do you have more info ?I tested it with 0.0.60-mud and it works.

**Comment by bessa** [comment]
Hi adrien, we tested it me and greg, when greg restart mud on docker or switch/upgrade docker, client failed to ping the server nevertheless tun device is up.

**Comment by angt** [comment]
Is there only one client trying to connect to the server ?

**Comment by bessa** [comment]
just one and only.
