### ISSUE TITLE
mud zombie process after reboot

### ISSUE THREAD

**Issue by bessa** [angt/glorytun#16]
root@OpenWrt:~# ps |grep -i glo
 6340 root     18008 S    {glorytun-udp.sh} /bin/sh /usr/sbin/glorytun-udp.sh glorytun-udp keyfile /tmp/glorytun-udp.key
 6368 root         0 Z    [glorytun-udp]
19025 root      8520 S    grep -i glo

solved by restarting mud client side :/

**Comment by bessa** [comment]
![zombie-mud](https://cloud.githubusercontent.com/assets/20698949/17361526/3ec6b6dc-5971-11e6-9d4a-665e95f4eec0.png)

**Comment by angt** [comment]
There is no `fork()` in the code so the problem should be somewhere else.

**Comment by jedisct1** [comment]
![No fork](https://www.andreas-jung.com/contents/no-forks-please/image)
