### ISSUE TITLE
Setup glorytun-mud 

### ISSUE THREAD

**Issue by debiansid** [angt/glorytun#21]
Is there any manual for this?

**Comment by angt** [comment]
Not yet :) We still recommend the use of the TCP version.

**Comment by debiansid** [comment]
Ovh is on udp too?

**Comment by angt** [comment]
No, OVH currently uses the TCP version.

**Comment by debiansid** [comment]
from ovh source code on github, I have no idea how to setup glorytun and shadowsocks on otb, could you please kindly give me any idea?
thanks

**Comment by debiansid** [comment]
Ok glorytun tcp version is running, I will try glorytun-mud on my server and openwrt now

**Comment by hdid** [comment]
Did you can config mud version? TCP has poor speed in here..

**Comment by debiansid** [comment]
No ,not yet.
