### ISSUE TITLE
LEDE package and LUCI module

### ISSUE THREAD

**Issue by jedisct1** [angt/glorytun#22]
LEDE currently makes it quite easy to set up an OpenVPN or Wireguard VPN by installing the related packages, and LUCI modules (luci-app-wireguard).

Having Glorytun support as well would be dope.

**Comment by angt** [comment]
Yep :) I should give some love to [glorytun-openwrt](https://github.com/angt/glorytun-openwrt).

**Comment by angt** [comment]
[openmptcprouter](https://www.openmptcprouter.com) have something like this, I put it here to remember :)
![img](https://www.openmptcprouter.com/img/screenshots/Screenshot_20180209_171531.png)
