### ISSUE TITLE
glorytun(mud version) is not pingable

### ISSUE THREAD

**Issue by ekenchan** [angt/glorytun#24]
tun devices were up on both server and client sides, and
on server:
ip addr add 192.168.99.1 peer 192.168.99.2 dev gt-tun

on client:
ip addr add 192.168.99.2 peer 192.168.99.1 dev gt-tun

but pinging 192.168.99.1 on client side  was stuck

**Comment by angt** [comment]
Hi,
Did you setup the bind option on the server side ?
Regards

**Comment by ekenchan** [comment]
no, but I ran tcpdump on client side, and found that no packets were sent to server port

client side command line:

glorytun host <server ip> port 998 dev  gt-tun mtu-auto keyfile <keyfile> chacha20

**Comment by angt** [comment]
Ok, so you have to setup the bind option on the server side.
And when you run tcpdump make sure something sends packets in the tunnel.

**Comment by ekenchan** [comment]
server command line:
glorytun bind-port 998 dev gt-tun mtu-auto keyfile [keyfile] chacha20

**Comment by angt** [comment]
You have to change to something like `glorytun bind [BIND_IP] bind-port ...`

**Comment by angt** [comment]
As mud doesn't create path for `0.0.0.0`
