### ISSUE TITLE
Disable encryption

### ISSUE THREAD

**Issue by lars18th** [angt/glorytun#25]
Hi,

Why this request #14 is discarded?

In several scenarios the use of encryption limits the performance. So, have the option for disable it has sense.

Is there any possibility to consider implementing this option?

**Comment by angt** [comment]
Hi @lars18th,
@jedisct1 works very hard to make libsodium as fast as possible.
Can you post the output of the command `glorytun bench` and your arch ?
Thanks

**Comment by angt** [comment]
Hi, why do you need glorytun with your other tunnels ?
As sodium is really fast, maybe you should disable encryption on your other tunnels ?

**Comment by lars18th** [comment]
Hi @angt ,

Thank you for your answer!

> Hi, why do you need glorytun with your other tunnels ?
> As sodium is really fast, maybe you should disable encryption on your other tunnels ?

Because the encryption goes best in the _lower layer_. Then, the traffic is externaly just only _one_ stream. And when the Glorytun runs over the tunnel, plus other traffic, no one can intercept or show on it. Futhermore, these tunnels have hardware acceleration and integrity checking, plus timestamps.

So, from my point of view, having the option for running without encryption is a very useful functionality.

I hope you like to consider it.
Regards.

**Comment by angt** [comment]
Hi, still not convinced :)
We also have hardware acceleration (aesni, pclmul, ...), integrity checking, timestamp checking, perfect forward secrecy (1h by default) and other stuff.
Also, on my laptop I can encrypt at 16Gbps, fast enough :)

**Comment by lars18th** [comment]
> Also, on my laptop I can encrypt at 16Gbps, fast enough :)

Yes on your _highend_ laptop... Consider this scenerio:

- Lower layer: Multiple Tunnels with hardware encryption (nearly at wire speed).
- Middle layer: Low-end hardware device with Glorytun over tunnels (100 mbps wire speed, max. 20mbps with encryption).

In this case, the encryption in the Glorytun layer is useless and it limits the bandwith.

Why not leave the user to decide wich level of privacy s/he needs to use?

**Comment by izomiac** [comment]
Hello, I thought I'd chime in on this with my usage case.  I tunnel all my traffic through wireguard to an external VPN service.  I also am deploying this to a router, which is rather limited in resources.  There are two ways to combine this with glorytun:

- Router -> Wireguard interface -> Glorytun -> (Multiple WAN connections) -> VPS -> Remote VPN

- Router -> Glorytun -> (Multiple WAN connections) -> VPS -> Wireguard -> Remote VPN

The first solution is going to take a performance hit from encrypting everything twice on embedded hardware.  That's a steep cost for zero benefit.  The second solution decrypts all traffic at the VPS which I control, but do not have physical access to.  If the VPS is compromised (e.g. by someone infiltrating the host, which does happen on occasion) then all traffic is subject to being intercepted.  Plus there's an unnecessary decryption/reencryption that's likely to cause a performance hit on the el cheapo VPS I use.  (Using a dedicated VPN service plus a cheap VPS for other tasks is cheaper per Mbs than running a higher performance VPS in my experience.)

**Comment by angt** [comment]
Hi all,
I'm closing this as i can't help.
Mixing VPN is a bad idea so if you're looking for a multipath VPN with "zero-down" failover, just use glorytun (or mlvpn).
Regards.
