### ISSUE TITLE
glorytun (mud version) compiled on mipsel platform did not work

### ISSUE THREAD

**Issue by ekenchan** [angt/glorytun#26]
EINVAL returned when calling mud_send_path(). Actually sendmsg() got EINVAL

**Comment by angt** [comment]
Hi,
Glorytun should work on mipsel,
which kernel and what libc did you use ?

**Comment by ekenchan** [comment]
kernel 3.4.x
uclibc

**Comment by angt** [comment]
I've tested master on mipsel (with qemu-system-mipsel -M malta) and glorytun works.
So it's not related to mipsel but i used a 4.14 kernel with musl.
