### ISSUE TITLE
There may be a issue in the glorytun/src/bind.c.

### ISSUE THREAD

**Issue by LJNL** [angt/glorytun#27]
Hi devs, it may exist underlying memory-leak problem. When I read the file bind.c, I found that it will apply some space by malloc in the line 144. However, when it goes to line 156 and the 'mud' points to null, then the function will return directly not give the 'buf' space back to system. There is also something similar to that in the following lines.

**Comment by angt** [comment]
Hi LJNL,
Thanks a lot for taking the time to write this issue (and read the code).
The code is not very readable but the return you pointed out (at line 158) is like an exit.
You can see this here: https://github.com/angt/glorytun/blob/master/src/main.c#L76
The kernel will take care of it for us :)
Regards
