### ISSUE TITLE
Is this suited for aggregation of two variable speed connections?

### ISSUE THREAD

**Issue by ilmaisin** [angt/glorytun#30]
I'd like to ask if this program is suitable for aggregation of two connections with variable speed. For example, a cable modem connection and a mobile broadband, or two mobile broadbands from two different carriers? Can I just omit the rate limit thing from the command?

**Comment by angt** [comment]
Hi,
Yes the rate tx/rx parameters allow to help the scheduler to aggregate correctly in this scenario.
Soon theses parameters will be dynamically guessed but for 0.1.0 they are mandatory.

**Comment by angt** [comment]
Hi,
I created a new issue to track this point: #51.
