### ISSUE TITLE
PKI: one server keys + multiple clients keys

### ISSUE THREAD

**Issue by LovingFox** [angt/glorytun#32]
Does this project support PKI for secure communications? Like OpenVPN: server instance with server key and multiple client instances each with own key.

**Comment by angt** [comment]
Hi,
I preferred a secret key auth setup, for simplicity (and legacy) at the beginning of the project.
glorytun already uses P(ephemeral)K for encryption, so it is very easy to add PK auth.
But a full PKI setup, with revocation, is not planned for now.
Best regards.

**Comment by LovingFox** [comment]
@angt thx

Does this mean if I want make star topology (server is a center and many remote spokes) I have to run multiple instance of glorytun
daemon on a server side, one instance per spoke? And every instance will use one uniq UDP port. Is it true?

**Comment by angt** [comment]
Yes, exactly.
