### ISSUE TITLE
Add AES-128-GCM

### ISSUE THREAD

**Issue by uryupinsk** [angt/glorytun#33]
Hello,

Thanks for Glorytun, it's wonderful. I'm using it with the OpenMPTCProuter project. Currently, I use the AES-256-GCM encryption but I would like an AES-128-GCM because it's less CPU intensive for an almost unbreakable encryption method by today's computer power.

Best regards

**Comment by angt** [comment]
Hi,
With AES-NI, AES-256-GCM should not be the bottleneck.
Can you run `glorytun bench` on your router to see how AES is performing ?

**Comment by uryupinsk** [comment]
This is the result of `glorytun bench`:

```
bench: aes256gcm
     8 bytes     75.04 Mbps
    16 bytes    152.47 Mbps
    32 bytes    278.12 Mbps
    64 bytes    476.83 Mbps
   128 bytes   1038.14 Mbps
   256 bytes   1321.30 Mbps
   512 bytes   1536.74 Mbps
  1024 bytes   1674.50 Mbps
  2048 bytes   1760.21 Mbps
  4096 bytes   1792.89 Mbps
  8192 bytes   1814.95 Mbps
 16384 bytes   1816.48 Mbps
 32768 bytes   1819.42 Mbps
```

I know it is not bottlenecked, but I would like the AES-128-GCM option for it to be a bit less CPU intensive, as I use the server for other things than glorytun.

**Comment by angt** [comment]
Glorytun uses a 256 bits secret key for simplicity (the same key is used for all methods) and the win in perf would be very small (only few less rounds).

**Comment by uryupinsk** [comment]
I guess you're right. Maybe it would have a greater impact on non AES-NI CPU, but in that case Chacha20 seems to be the better option.

**Comment by angt** [comment]
Ok, closing :)
Also, ChaCha20 is forced when AES-NI is not present because it is very difficult and inefficient to do AES correctly (in constant time) without it. Fast table-based implementation are all insecure..
