### ISSUE TITLE
path: Invalid argument

### ISSUE THREAD

**Issue by Hello71** [angt/glorytun#35]
no matter what I try I get "path: Invalid argument" when executing the "glorytun path" command, except when I set "dev eth0" in which case I get "path: No such file or directory".

**Comment by angt** [comment]
Hi,
Does the command `glorytun show` output something ?

**Comment by Hello71** [comment]
I didn't read the instructions good, I missed the "to SERVER_IP". I think it would be good to have a better error message though, even something like "maybe glorytun is in client mode, check that you specified 'to Y' in bind command"

**Comment by angt** [comment]
Yes, I'll improve that :)
