### ISSUE TITLE
Query On Multipathing

### ISSUE THREAD

**Issue by jeetu28** [angt/glorytun#36]
I was looking at something to provide a way for multi path udp. I came across Glorytun, But i have few query to confirm:
a) Does it provide the multi-path feature across available multiple interface like Multipath TCP provides?
b) how does it select the interface to be used to establish the tunnel and include in multi path list?

**Comment by angt** [comment]
Hi,
Yes, glorytun allows you to use all your paths like mptcp,
you can add or delete a path with the command `glorytun path`.
Note that you have to configure all interfaces in the same way as with mptcp.

**Comment by jeetu28** [comment]
Thank you for your reply on this!!
how can i remove a degraded path from the list? what is the exact command?
![snap](https://user-images.githubusercontent.com/48015690/59917659-202abb80-9440-11e9-820d-bcde1be2cd19.JPG)

**Comment by angt** [comment]
you just down it:
`glorytun path 95.69.111.135 down`

**Comment by angt** [comment]
Next release will fully remove a down path after server sync.

**Comment by jeetu28** [comment]
Okay!!
Thanks!!
