### ISSUE TITLE
Any TCP only solution?

### ISSUE THREAD

**Issue by ookangzheng** [angt/glorytun#37]
My Uni will block all outgoing UDP by default. Anyway to convert UDP to make TCP likes to bypass firewall?

**Comment by angt** [comment]
Hi,
I started with a TCP version and it was very hard to get a smooth TCP connectivity.
We could pretend to be a TCP session (like [this](https://github.com/wangyu-/udp2raw-tunnel)) but it is a lot of work and not the current target.
Regards

**Comment by angt** [comment]
It is maybe not so hard to pipe `glorytun` with `udp2raw-tunnel` to get what you want.

**Comment by ioogithub** [comment]
[angt](https://github.com/angt) I am confused about tcp, openmptcprouter uses glorytun tcp as the default VPN tunnel. In the default configuration this would be for any traffic other than TCP (udp, icmp etc.) When the router is using glorytun tcp it is unstable, connection speeds are typically 250 kbps even on fast wan connections and it disconnects often. If tcp not supported at all?

There is an option to use glorytun udp, should I?
