### ISSUE TITLE
Always degraded path status

### ISSUE THREAD

**Issue by AliveDevil** [angt/glorytun#40]
Server sequence:
```
glorytun bind 0.0.0.0 keyfile my_secret_key &
ifconfig tun0 172.25.0.1 pointopoint 172.25.0.2 up
```

Client sequence:
```
glorytun bind 0.0.0.0 to x.x.x.x keyfile my_secret_key &
ifconfig tun0 172.25.0.2 pointopoint 172.25.0.1 up
glorytun path up 172.16.0.20
glorytun path up 192.168.2.20
```

Client has following addresses:
WAN1: 192.168.2.20/24 (gateway is 192.168.2.1)
WAN2: 172.16.0.20/24 (gateway is 172.16.0.1)

`glorytun path` always shows degraded status on client.

Is it possible to get some hints to getting this work? How is "LOCAL_IPADDR" to be understood with a multi-wan setup?

> `ip a`
```
2: enp0s20u4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 00:e0:4c:36:44:69 brd ff:ff:ff:ff:ff:ff
    inet 192.168.178.129/24 brd 192.168.178.255 scope global dynamic noprefixroute enp0s20u4
       valid_lft 4671sec preferred_lft 4671sec
    inet6 fe80::3e11:ccc5:5dd2:7bef/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
40: fb@enp0s20u4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:e0:4c:36:44:69 brd ff:ff:ff:ff:ff:ff
    inet 172.16.0.20/24 brd 172.16.0.255 scope global noprefixroute fb
       valid_lft forever preferred_lft forever
    inet6 fe80::a5ee:8b81:7ec6:c38e/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
41: sph@enp0s20u4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:e0:4c:36:44:69 brd ff:ff:ff:ff:ff:ff
    inet 192.168.2.20/24 brd 192.168.2.255 scope global noprefixroute sph
       valid_lft forever preferred_lft forever
    inet6 fe80::56ad:eda:a116:23f7/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
```
(fb and sph are WAN1/WAN2)

**Comment by angt** [comment]
Hi, you have to setup rate for each path.
like `glorytun path X.X.X.X up rate tx 1M rx 20M`.
This is needed for the scheduler to work correctly.

**Comment by AliveDevil** [comment]
I assume the server does not need to know any path, right? The connection is established directly from client to server.

These are all IP/path configurations I'm aware of which are available to this system (client):
```
glorytun path <Server IP> up rate tx 28mbit rx 72mbit
glorytun path <Server IP> up rate tx 4mbit rx 16mbit
```

WAN1:
```
glorytun path 172.16.0.1 up rate tx 28mbit rx 72mbit
glorytun path 172.16.0.20 up rate tx 28mbit rx 72mbit
```

WAN2:
```
glorytun path 192.168.2.1 up rate tx 4mbit rx 16mbit
glorytun path 192.168.2.20 up rate tx 4mbit rx 16mbit
```

```
# glorytun path
path UP
  status:   DEGRADED
  bind:     <Server IP> port 5000
  public:   - port 0
  peer:     <Server IP> port 5000
  mtu:      1302 bytes
  rtt:      0.000 ms
  rttvar:   0.000 ms
  rate tx:  3500000 bytes/sec
  rate rx:  9000000 bytes/sec
  total tx: 82 packets
  total rx: 0 packets
path UP
  status:   DEGRADED
  bind:     172.16.0.1 port 5000
  public:   - port 0
  peer:     <Server IP> port 5000
  mtu:      1302 bytes
  rtt:      0.000 ms
  rttvar:   0.000 ms
  rate tx:  3500000 bytes/sec
  rate rx:  9000000 bytes/sec
  total tx: 43 packets
  total rx: 0 packets
path UP
  status:   DEGRADED
  bind:     172.16.0.20 port 5000
  public:   - port 0
  peer:     <Server IP> port 5000
  mtu:      1302 bytes
  rtt:      0.000 ms
  rttvar:   0.000 ms
  rate tx:  3500000 bytes/sec
  rate rx:  9000000 bytes/sec
  total tx: 28 packets
  total rx: 0 packets
path UP
  status:   DEGRADED
  bind:     192.168.2.1 port 5000
  public:   - port 0
  peer:     <Server IP> port 5000
  mtu:      1302 bytes
  rtt:      0.000 ms
  rttvar:   0.000 ms
  rate tx:  500000 bytes/sec
  rate rx:  2000000 bytes/sec
  total tx: 11 packets
  total rx: 0 packets
path UP
  status:   DEGRADED
  bind:     192.168.2.20 port 5000
  public:   - port 0
  peer:     <Server IP> port 5000
  mtu:      1302 bytes
  rtt:      0.000 ms
  rttvar:   0.000 ms
  rate tx:  500000 bytes/sec
  rate rx:  2000000 bytes/sec
  total tx: 8 packets
  total rx: 0 packets
```
ifconfig for tun0:
```
tun0: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1280
        inet 172.25.0.2  netmask 255.255.255.255  destination 172.25.0.1
        inet6 fe80::1064:caed:4213:d542  prefixlen 64  scopeid 0x20<link>
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 500  (UNSPEC)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by angt** [comment]
Yes, on the client you have to first `bind 0.0.0.0 to SERVER_IP`
then do the `path LOCAL_IP up rate ...`.

Glorytun didn't received any packet.
You should check that routing is ok:
`ip route get SERVER_IP from 172.16.0.20` should give `172.16.0.1`
and ping:
`ping -I 172.16.0.20 SERVER_IP`

**Comment by AliveDevil** [comment]
Okay so …
It looks like the system is doing something … weird:
```
$ ip route get x.x.x.x from 172.16.0.20
x.x.x.x from 172.16.0.20 via 172.16.0.1 dev fb uid 1000
    cache
$ ip route get x.x.x.x from 192.168.2.20
x.x.x.x from 192.168.2.20 via 172.16.0.1 dev fb uid 1000
    cache
```
Like there is just one path available.
This is IP route (I disabled default route creation and created two routes for each interface to my server):
```
x.x.x.x via 172.16.0.1 dev fb proto static metric 402
x.x.x.x via 192.168.2.1 dev sph proto static metric 403
```
So first route takes precedence. Is there anything at this point where I can get this multipath up with a single target ip?

**Comment by angt** [comment]
The simplest way to handle that is by creating a routing table for each path.
You have to setup a rule (with `ip rule`) to select the correct table from the src ip.
Multi-path setup are quite hard to get right the first time. You can look at https://github.com/ovh/overthebox-feeds/blob/master/overthebox/files/bin/otb-check-config to see how we automate this in overthebox.

**Comment by AliveDevil** [comment]
Okay, found how to configure the routes/interfaces:
```
ip rule add from local-wan1-ip table wan1
ip rule add from local-wan2-ip table wan2
ip route add default via local-wan1-gw dev wan1 table wan1
ip route add default via local-wan2-gw dev wan2 table wan2
```
Path is now up and running. Unfortunately I do see some issues with performance though.
Following is local to remote:
```
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  14.7 MBytes  12.4 Mbits/sec  142             sender
[  5]   0.00-10.00  sec  14.5 MBytes  12.2 Mbits/sec                  receiver
```
and remote to local:
```
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  3.65 MBytes  3.06 Mbits/sec  111             sender
[  5]   0.00-10.00  sec  3.53 MBytes  2.96 Mbits/sec                  receiver
```
According to glorytun path it should roughly combine to `(16/4) + (72/28)` (in mbit/s) or `(2/0.5) + (9/3.5)` (in mbyte/s) or `11/4` (in mbyte/s).
```
# glorytun path
path UP
  status:   OK
  bind:     172.16.0.20 port 5000
  public:   <wan1 ip> port 27737
  peer:     <server ip> port 5000
  mtu:      1472 bytes
  rtt:      45.836 ms
  rttvar:   7.499 ms
  rate tx:  3670016 bytes/sec
  rate rx:  9437184 bytes/sec
  total tx: 34707 packets
  total rx: 30243 packets
path UP
  status:   OK
  bind:     192.168.2.20 port 5000
  public:   <wan2 ip> port 5000
  peer:     <server ip> port 5000
  mtu:      1464 bytes
  rtt:      87.837 ms
  rttvar:   1.123 ms
  rate tx:  512000 bytes/sec
  rate rx:  2097152 bytes/sec
  total tx: 5522 packets
  total rx: 6222 packets
```
Admitted there is atleast double the latency on my slower network but that does not correlate with the 2-3 MBit/s receiving iperf3-test.

Client specifications:
Atom x5-Z8300 (4x1,8 GHz), 4 GB Memory, Fedora 30
hTop while sending:
![image](https://user-images.githubusercontent.com/734738/61828123-44761f80-ae66-11e9-869c-a524f1183aad.png)

hTop while receiving:
![image](https://user-images.githubusercontent.com/734738/61828168-5952b300-ae66-11e9-9256-3db8dc8a845b.png)

On both machines (vps and local) I get easily above 1 GBit encryption speed.
I'd be really happy if it'd go 20 up and 50 down (as the network interface is only capable of 100 MBit (don't know if full-duplex: RTL8152)

**Comment by angt** [comment]
Good, could you run iperf in UDP (`-u -b 100M`) ? To check if it's a TCP issue ?

**Comment by AliveDevil** [comment]
Okay, I managed to get useable results (though not 100% what could be achieved, but close enough to what I'd want it to be).

One issue I'm having is though that I cannot seem to get any SSL-connection to Amazon Lightsail servers.
Router locally is configured with `iptables -t nat -A POSTROUTING -o gtc-tun0 -j MASQUERADE` and my VPS server (regardless of hoster: DigitalOcean, Vultr, Hetzner, OVH) is configured with `iptables -t nat -A POSTROUTING -o ens3 -j MASQUERADE`. All I get from cUrl to e.g. `eu-central-1-lightsail.cloudharmony.net` is `SSL Handshake failed, need more data`.
I assume there is a misconfiguration in my NAT …

**Comment by angt** [comment]
Nice :)
This look as an mss issue, try to setup the mss clamping on server side.
I'm closing for the current issue.
