### ISSUE TITLE
Quastion: MTU configuration for glorytun interface

### ISSUE THREAD

**Issue by LovingFox** [angt/glorytun#41]
I need to have tunnel aggregated by multiple Internet connections. But the mandatory requirement for me is MTU for the tunnel interface MUST be about 1524 bytes.

Is it possible to configure MTU of Glorytun? Something like an option "tun-mtu" in OpenVPN.

I must say right away that the TCP MSS configuration for the tunnel interface is not suitable for me. I just need to be able to transfer large IP-packets through the tunnel.

**Comment by angt** [comment]
Hi,
There is currently no option to force a larger than technically possible mtu (or fragmentation occurs). Could you explain why 1500 is mandatory in your case ?
Regards.

**Comment by LovingFox** [comment]
I need to use vxlan protocol (Openvswitch project) via tunnel. Vxlan encapsulates Ethernet frame into the ip-packet and forwards entire ip-packet without fragmentation as is. The standart Ethernet frame is 1518 byte size that leads to ip-Vxlan packet size is too big for the tunnel.

**Comment by angt** [comment]
I've never used OvS but maybe you can use glorytun directly to link your VM ?
If vxlan is really mandatory and you want glorytun then you must setup a small MTU..
