### ISSUE TITLE
how to setup point to point connection using ip command

### ISSUE THREAD

**Issue by loupzeur** [angt/glorytun#42]
Hello, I'm on archlinux and the ifconfig command has been removed ....

So I can't execute :
ifconfig tun0 10.0.1.1 pointopoint 10.0.1.2 up

What's the equivalent using the ip command ?
sudo ip addr add 10.10.10.1 dev tun1
sudo ip link set tun1 up

And then ? This doesn't allow any connection :/

**Comment by angt** [comment]
On arch, just call `glorytun-setup`, it should do the job but tbh I have not tested it for a while, so let me know :)

With iproute2, I generally setup glorytun this way:
```
ip tuntap add glorytun-server mode tun
ip addr add 10.166.178.3/31 dev glorytun-server
ip link set glorytun-server up
glorytun bind dev glorytun-server keyfile ...
```
and
```
ip tuntap add glorytun-client mode tun
ip addr add 10.166.178.2/31 dev glorytun-client
ip link set glorytun-client up
glorytun bind to <server-ip> dev glorytun-client keyfile ...
```
then you have to setup routes (or a table with rules) and your path.

**Comment by loupzeur** [comment]
ok thanks, i did forgot to define the route to the network of the tun (/31) ^^ :)
using the package from aur I don't have the glorytun-setup command, it's another package ? 
or it's not build by default ?

**Comment by angt** [comment]
It should be included, I'll check that for the next release (pretty soon)
