### ISSUE TITLE
add multi server ip bind support.

### ISSUE THREAD

**Issue by patrickkh7788** [angt/glorytun#44]
The server could use multi ip to accept the package to improve the speed. (for example the server  has 2 ip connect to 2 ISP)

**Comment by angt** [comment]
Yes, I also have a scenario for this too. But this need a change in the `glorytun path` command.

**Comment by patrickkh7788** [comment]
Is this able to work with ipv6 and ipv4 same time ?

**Comment by angt** [comment]
This feature is not planned for now and I didn't really think about it, but I guess it will work.

**Comment by patrickkh7788** [comment]
Is there an easy way to hard code the peers ip into source to test this ?  
(maybe only for multi server ipv4 only address ?)

**Comment by angt** [comment]
Commit f784348.
