### ISSUE TITLE
Packet loss issues, one WAN affects whole link.

### ISSUE THREAD

**Issue by Marctraider** [angt/glorytun#45]
Packet loss issues, one WAN affects whole link.

Sometimes one of my links experience upstream problems causing roughly ~50% packet loss, the whole aggregated link becomes bad quality because glorytun UDP keeps transmitting also over the bad link.

Also replicateable with netem and add artificial packet loss to one of the three WAN  interfaces. Anything I can do about this?

What about packet loss tolerance setting/timeout?

Edit: I see at 0.0.98 or something scheduler changed for more
bandwidth, i use bonding more for reliability.

**Comment by angt** [comment]
Is it real loss ? like 50% for any rate on the link ?

**Comment by Marctraider** [comment]
> Is it real loss ? like 50% for any rate on the link ?

I do ping test simply from client to outside, over glorytun udp. Once i create packet loss on one of the 3 wan's i see lot of dropped packets?

**Comment by angt** [comment]
I see two cases:
 - 50% drop at any rate, we can randomly duplicate packets (naively or by using some fontaincode). Or juste remove the path at a configured level. 
 - 50% drop at a specific rate and 0% at half the rate, glorytun will reduce the rate and will try to probe when the rate can goes up.

**Comment by Marctraider** [comment]
It is upstream noise I tried to fix it with ISP for 5 years sadly they still cant or wont solve it. Basically if upstream drops to near 0 there is average of 50% packet loss.

At any bandwidth rate if you mean that ;-)

Sadly most aggregation seems to all focus on maximum bandwidth potential, but im more seeking reliability/redundancy. Glorytun UDP seems great in theory, but if it keeps aggregating over a bad line and dont detect it, it can screw up realtime apps/games/voip big time.

**Comment by angt** [comment]
Yes it is clearly in the roadmap to handle bad links :)

Actually, glorytun already detects drop, but it doesn't detect if we are in case 1 or 2 so it does nothing for now.

**Comment by user747** [comment]
i run into this too on my adsl connections. some are on old lucent dslam, and others on newer lucent dslam. 

my modem will log when there is a rate change in the line (noise) and can be configured to output to remote rsyslog server. from there,  could scrape for rate changes and make adjustments to glory tun rate on the fly

**Comment by Marctraider** [comment]
Nice! I dont believe my modems can do that tho, customer locked :(

Also I noticed this: When I have all 3 WAN aggregated, and I put like 100ms artificial delay on WAN3, glorytun still use this path continuously, does it not take RTT into account?

**Comment by angt** [comment]
No, the rtt is not taken into account but it is planned for 0.3 (the "latency compensation" feature).
0.2 is about rate limiting and rate detection. 0.2.2 will automatically drop path with more than X% (X configurable).

**Comment by user747** [comment]
some test i do

6 idle wans with 30-60 rtt
![gt1](https://user-images.githubusercontent.com/25760697/66302079-49276d00-e8c6-11e9-804a-cf50cafe8ab7.png)

now to saturate 
![gt2](https://user-images.githubusercontent.com/25760697/66302144-63614b00-e8c6-11e9-94b2-9475d6cba1da.png)

1-5 stay under 100rtt 

our bad actor , 6, goes up to almost 400 rtt. 
aggregated download speed stays the same. aggregated upload under saturation reduces by 50-70%

this bad actor has a secret though. it is a dsl line set to interleave. all the rest are on FAST profiles

**Comment by angt** [comment]
You should reduce tx and/or rx rate to avoid congestion on this link.

**Comment by angt** [comment]
Do you have good aggregation on the first 5 links ?

**Comment by user747** [comment]
Actually this fix is much harder..... i have to call my ISP call center based in India, and tell them to switch it from interleave to fast. 

running 1-5 under saturation , with 6 removed, is buttery smooth

On rx tx side note: 
client shows 
rate tx:  100000 bytes/sec
rate rx:  700000 bytes/sec

vps shows:
rate tx:  700000 bytes/sec
rate rx:  0 bytes/sec

should they not mirror each other?

**Comment by angt** [comment]
On server side, rx rate is useless to know, we take all packets as we can.
You setup rx rate on client only to setup tx rate on the server.

**Comment by angt** [comment]
Loss detection has been merged on master :)
By default, a path with a loss > 10% are degraded.
The limit can be changed with `glorytun set losslimit`.

**Comment by Marctraider** [comment]
Nice, might try this.

Curious as to when a path is no longer degraded though. What if its set at 1% and detects 1%, would it go down and up continuously? or will it keep probing until no more packet loss is detected after some amount of time?

**Comment by angt** [comment]
Hi, loss is computed "smoothly" and flapping is somehow managed by this kind calculation.
But the current way to do it does not depend of the current rate and a fast link might be more likely to flap.
