### ISSUE TITLE
Redundant scheduler

### ISSUE THREAD

**Issue by Marctraider** [angt/glorytun#48]
Hi!

It would be great to see this (back? i think it once had such mode) in glorytun, maybe as option to choose scheduler? 

I use MPTCP for TCP aggregation, almost all high bandwidth transfer go via TCP.

For UDP, almost all data here is time sensitive and for realtime traffic. Since UDP is so little total bandwidth consumption when just using glorytun udp only for udp traffic, a redundant mode make sense. It would give realtime apps 99.99% uptime when dealing with bad links.

**Comment by angt** [comment]
Hi,
Before the new scheduler, glorytun was designed to minimize jitter (mostly VoIP).
To fix your problem I plan to implement something like RaptorQ (rfc6330) with the new multipath scheduler. You'll have the best of both worlds.

**Comment by Marctraider** [comment]
Sounds great! Looking forward to all the future improvements!

**Comment by angt** [comment]
Some people use https://github.com/wangyu-/UDPspeeder to solve this problem.
I like the idea to have a separate program to do this. I'll reopen if necessary.
