### ISSUE TITLE
Dynamic rate detection

### ISSUE THREAD

**Issue by angt** [angt/glorytun#51]
This is an important feature for LTE links.
Should be delivered in a 0.2.x as the new protocol was designed to do that.

**Comment by ITz-net** [comment]
this is a **very very very** important feature for LTE 4G

I tested in parallel mlvpn a slightly updated version from [markfoodyburton](https://github.com/zehome/MLVPN/issues/113), it also does not have dynamic bandwidth control, but mlvpn tries to solve this trouble with packet re-ordering, and realisation this leads to underloading ISP channels, so for example we loading file, on one interface, with ifstat we see 4.5 megabits and on the second 1.5 megabits, the situation all time changes, every second, then we see the 3 megabit equation occurs on both interfaces and then again re-ordering and everything on circle, as a result, the full band of both ISP is not used, at some point they gain speed about otherness, and then there is reordering.. 

Thus, we have good load balancing, but there is no aggregation, mlvpn has a fault tolerance mechanism when one of the ISP is lost or does not work well, but in reality often in such a situation it is necessary to restart the mlvpn client or server.

**Comment by angt** [comment]
Yes, Dynamic rate detection and latency compensation are the hot next topics :)

**Comment by angt** [comment]
If you setup cake on your tun interface (both sides) you can have a better experience too.

**Comment by ITz-net** [comment]
Adrien of course! congratulate you Happy New Year 2020!!! :-)

![image](https://user-images.githubusercontent.com/34165182/71582286-965c5900-2b1a-11ea-9ad0-6b8ad15b6613.png)

**Comment by angt** [comment]
I'm going to tag v0.3 with the current dynamic rate limiter, it is far from perfect but I need to test other part of the code before working on a better one :)
