### ISSUE TITLE
in Mini How-To you should add that rate tx and rx values are mandatory settings

### ISSUE THREAD

**Issue by bmullan** [angt/glorytun#52]
I configured everything but did not set rate tx 1mbit tx 20mbit
just executed:
\# glorytun path up x.x.x.x 
as I assumed there was some default.
But ping did not work.

Then I set an actual TX/RX and then Ping did work
\# glorytun path up LOCAL_IPADDR rate tx 1mbit rx 20mbit

So those 2 bandwidth options are required to be set to something.

**Comment by angt** [comment]
Thanks, I moved the mini how to to the [wiki](https://github.com/angt/glorytun/wiki).
