### ISSUE TITLE
Mini HowTo ? 

### ISSUE THREAD

**Issue by benoitc** [angt/glorytun#58]
I don't get how glorytun work...

what is 10.0.1.1 in the case of server and 10.0.1.2 ? 

 Where is run the command "glorytun path up <LOCAL_IP> rate tx 1mbit rx 20mbit" on the server?

**Comment by angt** [comment]
Hi,
For the server part (on Linux) you can take a look at https://github.com/angt/mudock/blob/master/run.
The `glorytun path up ...` is used on the client side to add a new path.
