### ISSUE TITLE
Can Glorytun implement a full mesh overlay

### ISSUE THREAD

**Issue by bmullan** [angt/glorytun#60]
Sorry if this has been asked before.
But looking in the wiki etc I didn't see anything alluding to it.

Thanks

**Comment by angt** [comment]
Hi,
No, It is only there to secure your connectivity and only one client can connect to one server.
But having a fullmesh setup is not very hard, just spawn many glorytun :)

**Comment by bmullan** [comment]
Thanks for the claification
