### ISSUE TITLE
Control Panel Crash but no error info in Ubuntu/Debian

### ISSUE THREAD

**Issue by angeldustneo** [angt/glorytun#61]
Hello :
I have met a problem about the panel/core crash ...

```
root@glorytun:~# glorytun path
path: No such file or directory
root@glorytun:~# glorytun show
show: No such file or directory
```

It happened some hour after one path have been setup everytime .

`gt-tun0: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1392`

```
root@glorytun:~# systemctl status glorytun@tun0
● glorytun@tun0.service - Glorytun on tun0
   Loaded: loaded (/lib/systemd/system/glorytun@.service; disabled; vendor preset: enabled)
   Active: active (running) since Sun 2020-03-22 11:57:09 CST; 8h ago
 Main PID: 30141 (glorytun)
   CGroup: /system.slice/system-glorytun.slice/glorytun@tun0.service
           └─30141 glorytun bind keyfile /etc/glorytun/tun0/key 0.0.0.0 5000 dev gt-tun0
```

using the lastest version 0.3.3 ...
I have tried debian 9 / ubuntu 16 ...Both of them have problem..
Please help .
And Please recommand a stable OS for glorytun .

Thank you.

**Comment by angt** [comment]
Hi,
I didn't touch the systemd setup since 0.1 I think.. I'll take a look soon!

**Comment by angeldustneo** [comment]
> Hi,
> I didn't touch the systemd setup since 0.1 I think.. I'll take a look soon!

I have tried running it in background without  systemed . 

The tunnel stop working just after a few minute
the process quit with no error log ...

When i using the systemed ..I can't control the tunnel , but it is alive and working well ...  so i think it may not the problem of systemd.


I have tried  glorytun 0.22 0.3.0 0.33  .
Both of them stop working a few min with debian9/ubuntu 16.04...

**Comment by angt** [comment]
I've tested on "Ubuntu 16.04.6 LTS" and it works.
I had to start the service systemd-networkd to configure tun interfaces.
I'll need more information, I don't think it is related to ubuntu/debian anymore.

**Comment by angt** [comment]
I'm closing, feel free to reopen the issue if needed.
