### ISSUE TITLE
Multi client Raspberry on 1 VPS

### ISSUE THREAD

**Issue by Florent4223** [angt/glorytun#66]
Hello,

My title sums up my question but in detail is that on a single VPS, it is possible to connect several clients (in my case raspberry) potentially at the same time which each will use several internet connections (4G or other) with Glorytun?

Another question at the same time: Can I launch Glorytun from a raspbian (Buster for example)?

Thanks

**Comment by angt** [comment]
Hi,

No, glorytun focuses on creating a single tunnel capable of handling many paths.
However, it is quite easy to configure many tunnels for many clients on a single vps.
You just have to change the binded port when starting the tunnel.
Each client will have its secret key/dedicated port to connect to.

Never used raspbian but it has to work :)

**Comment by Florent4223** [comment]
Thank you for the answer

this confirms what I supposed saw the how to

in fact on the raspbian it works too ... but you must activate the 64bits instructions (natively 32bits)
yes in the meantime I found sorry :)

if I understood correctly (in my case I would often have only 2 connections and 4G type):
glorytun creates a tunnel and passes the flow (TCP and UDP) of the 2 connections via this tunnel?

By cons I suppose that the overall latency will be that of the worst connection? (in the case of voip)

If yes can we determine THE 4G connection which is weaker to either "disconnect" or change it (for example test with another operator then repeat the test to see if the whole is better)?

thanks

**Comment by angt** [comment]
Glorytun will create a tunnel over all your path and your system will see it as a standard one path with a bigger jitter, but voip should be able to handle that most of the time. It will also enable/disable degraded path automatically.

For finer control you can use the command `glorytun path` to get some statistics about each path (bw, rtt, rttvar, loss, ...) and enable/disable path yourself.

Hope this help.

**Comment by Florent4223** [comment]
thanks
I'm trying to set up the tunnel.

I added my 1st connection:
./glorytun path up 192.168.9.3 rate tx 6mbit rx 6mbit 

Already my first question: in the case of a 4G connection with fairly random speed which rate should we put?

Connection is done, ping ok
path UP
  status:  OK
  bind:    192.168.9.3 port 5000
  public:  xx.1xx.1xx.1x0 port 5000
  peer:    9x.xx.xx.xx port 65000
  mtu:     1472 bytes
  rtt:     67.378 ms
  rttvar:  5.675 ms
  rate:    fixed
  losslim: 100
  beat:    100 ms
  tx:
    rate:  750000 bytes/sec
    loss:  1 percent
    total: 6802 packets
  rx:
    rate:  750000 bytes/sec
    loss:  0 percent
    total: 3263 packets

but when i add a 2nd connection:
./glorytun path up 192.168.100.3 rate tx 6mbit rx 6mbit

path UP
  status:  **DEGRADED**
  bind:    192.168.100.3 port 5000
  public:  - port 0
  peer:    xx.xx.xx.xx port 650xx
  mtu:     0 bytes
  rtt:     0.000 ms
  rttvar:  0.000 ms
  rate:    fixed
  losslim: 100
  beat:    100 ms
  tx:
    rate:  750000 bytes/sec
    loss:  0 percent
    total: 926 packets
  rx:
    rate:  750000 bytes/sec
    loss:  0 percent
    total: 0 packets

The ping always but clearly passes on only one of the 2 connections.

Do you have an idea?

Thanks

**Comment by angt** [comment]
Hi,

I'm sorry, I'm not really sure about your issue. But:
- The command `path` allows you to set the maximum rate in both directions for each link.
- You need to add a path for each link if you want aggregation to work.

**Comment by angt** [comment]
I hope you've fixed your problem.
Don't hesitate to reopen if necessary with more information if possible.
