### ISSUE TITLE
does glorytun support multi-client interaction

### ISSUE THREAD

**Issue by rjdpantara** [angt/glorytun#71]
Hi ,sorry for the silly question,
but does glorytun support multi-client with one vps,what configuration is required for dhcp to alloacate ip to all respective client, Also will it support client to client interaction through one vps

**Comment by angt** [comment]
Hello, there is no "silly question" don't worry :)

glorytun does one job: it creates a tunnel where many connections are aggregated to secure your connectivity.
It's not a VPN in the sense that you're going to create a private network over Internet like wireguard.

That said, you don't really need a dedicated tool for that.
You can simply create multiple glorytun servers on your VPS and connect each client to its own server (with its own key).
Then, by configuring the routing with the usual tools, you can get the same functionality.

**Comment by rjdpantara** [comment]
Hi ,Thanks for the quick reply, you saved my days,
Is there a way we have a single vps glorytun server and it acts as dhcp server and each glorytun client connects to it and gets an IP address to its tun0 assigned from the VPS(just like openvpn).This will simplify the use case as we do not know how many clients will be there in advance and configuration of each client and spawning each server is an overhead.

**Comment by angt** [comment]
Yes, you can look at the [systemd network config](https://github.com/angt/glorytun/blob/master/systemd/glorytun.network).
This will also automatically select a free /24 prefix for the server.

**Comment by rjdpantara** [comment]
Thanks a lot. Is there any similar configuration on openwrt? I guess the one you shared is ubuntu/linux specific

**Comment by angt** [comment]
Sorry for the late response,
I don't have this but you should be able to something similar on OpenWrt.
You can look at https://github.com/ovh/overthebox to see how things are done.
