### ISSUE TITLE
Question of using glorytun on raspberry pi

### ISSUE THREAD

**Issue by FovenX3** [angt/glorytun#85]
I followed MiniHowTo in wiki and #56 

Successful get ping from `ping 10.0.1.1` But unable to use internet from server.

I have two internet input to my raspberry pi. A 4g module(usb0, 192.168.225.24) and Ethernet(eth0, 192.168.2.2). When I plug the Eth cable in, can't connect internet from 4g module, even ping -I 192.168.225.24 google.com. With Ethernet and 4g module plugin, only if I add 192.168.225.24 as defult route, then I can use 4g module to conncet internet. But lost internet frome eth0 (192.168.2.2).

So this confused me when I add path to glorytun. In #56 , ITz-net said after added two path, run ping 10.0.1.1, the second path will show "status: OK"  But unless I set second path to default route using `route add default gw 192.168.225.24 `  The second path always stay **DEGRADED**

I'm compiled glorytun on raspberry 4, raspberry os, server using ubuntu.

**Comment by angt** [comment]
Hello,
It looks like a configuration issue..
Please check your setup with `ip route get <ADDR> from <ADDR>` for each path.
