### ISSUE TITLE
tap instead of tun?

### ISSUE THREAD

**Issue by ghost** [angt/glorytun#86]
Hi. I have been experimenting with glorytun and it looks really promising considering the bad experiences I had with mlvpn and openvpn bonding.

Although, is it possible to use tap layer 2 instead of tun layer 3 in order to be able to bridge interfaces? If so, how hard would it be to implement?

Right now I would have to setup a gretap within glorytun to do that, which I don't know if it's a good idea.

Thanks.

**Comment by angt** [comment]
Hi,
L2 is not planned at all, sorry.
glorytun is just a L3 tunnel, so yes, you can use gretap,vxlan,etc with it :)
Regards
