### ISSUE TITLE
port listen

### ISSUE THREAD

**Issue by zulu14** [angt/glorytun#87]
Hello ant,
thank for you awesome job, 

we try multiple time the glorytun (tcp version) from OMR and it works great,

I did not succeed in making glorytun udp market (this repo) whether in V0.035, in V0.2.2 or the last stable,

I manage to run the server (virgin kvm machine)

and client (debian 11 blank)

the interfaces are well created (ip a) but after adding the first path (with the TX RX defined) I have no message from GT indicating a connection attempt or whatever, but what to me calls out after having tested with KVM servers under debian, ubuntu from a different supplier I port 5000 bind of course 0.0.0.0 but it is never open with netstat, I have this behavior with all the versions, am I missing something?
![image](https://user-images.githubusercontent.com/71033768/134769105-1015ab02-c65d-4f26-a3e5-7e083cd3215e.png)

![image](https://user-images.githubusercontent.com/71033768/134769124-c4a046e1-676c-48d2-965c-d6e137427ec0.png)

**Comment by zulu14** [comment]
![image](https://user-images.githubusercontent.com/71033768/134769189-fcd51888-5d7c-4146-b0e2-0a0266b89e70.png)

**Comment by angt** [comment]
Hello,
I'm not really sure about your question, but with `ss` or `netstat` I see the port:

<img src="https://user-images.githubusercontent.com/13289655/135404937-1be114b8-eed0-4251-bfe1-9c054237049c.png">
